# Generated by Django 3.0 on 2019-12-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191114_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('F', 'Filler'), ('filme', 'Filme'), ('ova', 'OVA')], max_length=200),
        ),
    ]
